// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddmhkjdrholugwnodqmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbWhramRyaG9sdWd3bm9kcW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDAwMzAsImV4cCI6MjA2MTA3NjAzMH0.IDk9e7WtGPWenA0lWmrn4pkdDpdC7ZzA9wH2eJhZG4s";



export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);